// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApF0VTbeOUt46zesQv8uAcBKXX7fwiaCI',
    appId: '1:783312787529:web:d423c8e7e63b9ec1630798',
    messagingSenderId: '783312787529',
    projectId: 'sorukutusu-ccd38',
    authDomain: 'sorukutusu-ccd38.firebaseapp.com',
    storageBucket: 'sorukutusu-ccd38.firebasestorage.app',
    measurementId: 'G-VT6NBTCEZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDje7dnoQVyjhywTNh6w2JtgaGZDLjjAvY',
    appId: '1:783312787529:android:b83eed82efbc028d630798',
    messagingSenderId: '783312787529',
    projectId: 'sorukutusu-ccd38',
    storageBucket: 'sorukutusu-ccd38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe-YIKrnTeiWyMoKvf3ksB5aCgPPs2M7E',
    appId: '1:783312787529:ios:8e017d44ac5ecea9630798',
    messagingSenderId: '783312787529',
    projectId: 'sorukutusu-ccd38',
    storageBucket: 'sorukutusu-ccd38.firebasestorage.app',
    iosBundleId: 'com.example.soruKutusuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe-YIKrnTeiWyMoKvf3ksB5aCgPPs2M7E',
    appId: '1:783312787529:ios:8e017d44ac5ecea9630798',
    messagingSenderId: '783312787529',
    projectId: 'sorukutusu-ccd38',
    storageBucket: 'sorukutusu-ccd38.firebasestorage.app',
    iosBundleId: 'com.example.soruKutusuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApF0VTbeOUt46zesQv8uAcBKXX7fwiaCI',
    appId: '1:783312787529:web:f904c800e37dc3a2630798',
    messagingSenderId: '783312787529',
    projectId: 'sorukutusu-ccd38',
    authDomain: 'sorukutusu-ccd38.firebaseapp.com',
    storageBucket: 'sorukutusu-ccd38.firebasestorage.app',
    measurementId: 'G-926BCYKJVC',
  );
}
